speech_rate: 240    # characters per minute


body:
  bust_size: 98     # cm
  cloth_len: 68     # cm
  shoulder_width: 42      # cm

  pants_len: 100    # cm
  shoe_size: 40     # EU size


update_date:
  zotero: 2025-11-03
  wechat:
    # ~/wxid_yysjo0g4xjjn22_a74f
    # rm: business/migrate
    _backup: 2026-07-12
    _clean: 2026-06     # msg
