Essential:
  ADrive: https://www.alipan.com/
  Google Chrome: https://www.google.com/chrome/
  Office: https://sustech.online/service/#非官方windows套件激活服务
  ToDesk: https://www.todesk.com/
  WPS Office: https://www.wps.cn/
  XiangRiKui: https://sunlogin.oray.com/
  Zotero: https://www.zotero.org/

Tencent:
  QQ: https://im.qq.com/index/
  QQ Music: https://y.qq.com/
  WeChat: https://weixin.qq.com/
  WeMeet: https://meeting.tencent.com/

Programming:
  CUDA Toolkit: https://developer.nvidia.com/cuda-toolkit-archive   # --silent --toolkit --override --toolkitpath=<*/cuda-12.8>
  Docker: https://www.docker.com/
  Git: https://git-scm.com/
  MikTeX: https://miktex.org/
  MiniConda: https://www.anaconda.com/docs/getting-started/miniconda/install
  Strawberry Perl: https://strawberryperl.com/
  Visual Studio: https://visualstudio.microsoft.com/zh-hans/

Photo:
  Adobe: https://www.yuque.com/yihulaojiu-gsfg9/zz2qv5/boe117axkcecw77
  Capcut: https://www.capcut.cn/
  Sequator: https://www.softpedia.com/get/Multimedia/Graphic/Graphic-Others/Sequator.shtml
  Siril: https://siril.org/

Other-tools:
  # Clash: https://github.com/XiaMooo/Clash-for-Windows-zh-Linux-Arch
  EV Capture: https://www.ieway.cn/
  Hiddify: https://github.com/hiddify/hiddify-app
  TickTick: https://www.dida365.com/
  vivo Office: https://pc.vivo.com/#/


Configuration:

  Docker-daemon (/etc/docker/daemon.json):
    "registry-mirrors": [
      "https://docker.mirrors.ustc.edu.cn",
      "https://docker.1ms.run",
      "https://docker.udayun.com",
      "https://dockerpull.com"
    ]

  Excel2LaTeX: https://www.ctan.org/tex-archive/support/excel2latex

  # Memory-Settings
  # Registry: run.processes.with.pty = False
  JetBrains-plugins: [
    "GitHub Copilot", "GLB Viewer", "Markdown Editor", "PDF Viewer", "TeXiFy-IDEA", "Translation"
  ]

  Nice-fonts: [
    "Cambria Math", "Candara", "Dubai", "Footlight MT Light", "Times New Roman"
  ]

  # VcXsrv/X0.hosts: Host IP address list
  #   docker: DISPLAY=host.docker.internal:$NUM
  #   ssh: DISPLAY=$HOST:$NUM
  VcXsrv: https://sourceforge.net/projects/vcxsrv/files/

  # WebDAV: https://infini-cloud.net/en/index.html
  Zotero-plugins: [
    "https://github.com/retorquere/zotero-better-bibtex",
    "https://github.com/northword/zotero-format-metadata",
    "https://github.com/windingwind/zotero-pdf-translate",
    "https://github.com/federicotorrielli/zotero-metadata-hunter",
  ]
